/* gl31.c - tabla de despacho: nombre GL de escritorio -> implementacion gl31_* */
#include "gl31.h"
#include <stdio.h>
#include <string.h>

/* gl31_init / gl31_shutdown y la instancia gl31_be viven en gl31_caps.c */

typedef struct { const char* name; void* fn; } gl31_entry_t;
#define D(n) { #n, (void*)gl31_##n }

static const gl31_entry_t gl31_table[] = {
    D(glGetError), D(glEnable), D(glDisable), D(glIsEnabled), D(glPrimitiveRestartIndex),
    D(glGenSamplers), D(glDeleteSamplers), D(glBindSampler), D(glSamplerParameteri),
    D(glSamplerParameterf), D(glIsSampler), D(glGetSamplerParameteriv),
    D(glGenVertexArrays), D(glDeleteVertexArrays), D(glBindVertexArray), D(glIsVertexArray),
    D(glVertexAttribPointer), D(glVertexAttribIPointer), D(glEnableVertexAttribArray),
    D(glDisableVertexAttribArray), D(glVertexAttribDivisor),
    D(glGenBuffers), D(glDeleteBuffers), D(glBindBuffer), D(glBufferData), D(glBufferSubData),
    D(glBufferStorage), D(glBindBufferBase), D(glBindBufferRange), D(glCopyBufferSubData),
    D(glMapBuffer), D(glMapBufferRange), D(glUnmapBuffer), D(glGetBufferParameteriv), D(glIsBuffer),
    D(glGenTextures), D(glDeleteTextures), D(glBindTexture), D(glActiveTexture),
    D(glTexParameteri), D(glTexStorage2D), D(glTexStorage3D),
    D(glDrawArrays), D(glDrawElements), D(glDrawArraysInstanced), D(glDrawElementsInstanced),
    D(glDrawRangeElements), D(glMultiDrawArrays), D(glMultiDrawElements),
    D(glGetUniformBlockIndex), D(glUniformBlockBinding), D(glGetActiveUniformBlockiv),
    D(glGetActiveUniformBlockName), D(glGetUniformIndices), D(glGetActiveUniformsiv),
    D(glGetIntegeri_v),
    D(glCreateTextures), D(glBindTextureUnit), D(glTextureParameteri), D(glTextureParameterf),
    D(glTextureParameteriv), D(glTextureParameterfv), D(glTextureParameterIiv), D(glTextureParameterIuiv),
    D(glGetTextureParameteriv), D(glGetTextureParameterfv), D(glGetTextureParameterIiv), D(glGetTextureParameterIuiv),
    D(glGetTextureLevelParameteriv), D(glGetTextureLevelParameterfv), D(glGenerateTextureMipmap), D(glTextureStorage1D),
    D(glTextureStorage2D), D(glTextureStorage3D), D(glTextureStorage2DMultisample), D(glTextureStorage3DMultisample),
    D(glTextureBuffer), D(glTextureBufferRange), D(glTextureSubImage1D), D(glTextureSubImage2D),
    D(glTextureSubImage3D), D(glCompressedTextureSubImage1D), D(glCompressedTextureSubImage2D), D(glCompressedTextureSubImage3D),
    D(glCopyTextureSubImage1D), D(glCopyTextureSubImage2D), D(glCopyTextureSubImage3D), D(glGetTextureImage),
    D(glGetCompressedTextureImage), D(glCreateBuffers), D(glNamedBufferData), D(glNamedBufferStorage),
    D(glNamedBufferSubData), D(glGetNamedBufferSubData), D(glGetNamedBufferParameteriv), D(glGetNamedBufferParameteri64v),
    D(glGetNamedBufferPointerv), D(glClearNamedBufferData), D(glClearNamedBufferSubData), D(glMapNamedBuffer),
    D(glMapNamedBufferRange), D(glUnmapNamedBuffer), D(glFlushMappedNamedBufferRange), D(glCopyNamedBufferSubData),
    D(glCreateFramebuffers), D(glNamedFramebufferRenderbuffer), D(glNamedFramebufferTexture), D(glNamedFramebufferTextureLayer),
    D(glNamedFramebufferDrawBuffer), D(glNamedFramebufferDrawBuffers), D(glNamedFramebufferReadBuffer), D(glNamedFramebufferParameteri),
    D(glGetNamedFramebufferParameteriv), D(glGetNamedFramebufferAttachmentParameteriv), D(glCheckNamedFramebufferStatus), D(glInvalidateNamedFramebufferData),
    D(glInvalidateNamedFramebufferSubData), D(glClearNamedFramebufferiv), D(glClearNamedFramebufferuiv), D(glClearNamedFramebufferfv),
    D(glClearNamedFramebufferfi), D(glBlitNamedFramebuffer), D(glCreateRenderbuffers), D(glNamedRenderbufferStorage),
    D(glNamedRenderbufferStorageMultisample), D(glGetNamedRenderbufferParameteriv), D(glCreateVertexArrays), D(glVertexArrayElementBuffer),
    D(glVertexArrayVertexBuffer), D(glVertexArrayVertexBuffers), D(glVertexArrayAttribFormat), D(glVertexArrayAttribIFormat),
    D(glVertexArrayAttribLFormat), D(glVertexArrayAttribBinding), D(glVertexArrayBindingDivisor), D(glEnableVertexArrayAttrib),
    D(glDisableVertexArrayAttrib), D(glGetVertexArrayiv), D(glGetVertexArrayIndexediv), D(glCreateSamplers),
    D(glCreateProgramPipelines), D(glCreateQueries), D(glCreateTransformFeedbacks), D(glTransformFeedbackBufferBase),
    D(glTransformFeedbackBufferRange), D(glGetGraphicsResetStatus),
    D(glQueryCounter), D(glGetQueryObjecti64v), D(glGetQueryObjectui64v),
    D(glBeginQueryIndexed), D(glEndQueryIndexed), D(glGetQueryIndexediv),
    D(glBindFragDataLocationIndexed), D(glGetFragDataIndex),
    D(glVertexAttribP1ui), D(glVertexAttribP2ui), D(glVertexAttribP3ui), D(glVertexAttribP4ui),
    D(glVertexAttribP1uiv), D(glVertexAttribP2uiv), D(glVertexAttribP3uiv), D(glVertexAttribP4uiv),
    D(glGenQueries), D(glDeleteQueries), D(glIsQuery), D(glBeginQuery), D(glEndQuery),
    D(glGetQueryiv), D(glGetQueryObjectuiv), D(glGetQueryObjectiv),
    D(glGetString), D(glGetStringi), D(glGetIntegerv),
    D(glCreateShader), D(glShaderSource), D(glCompileShader), D(glGetShaderiv),
    D(glGetShaderInfoLog), D(glDeleteShader), D(glCreateProgram), D(glAttachShader),
    D(glDetachShader), D(glLinkProgram), D(glGetProgramiv), D(glGetProgramInfoLog),
    D(glUseProgram), D(glDeleteProgram), D(glBindAttribLocation), D(glGetAttribLocation),
    D(glGetUniformLocation),
    D(glTexBuffer), D(glBindFragDataLocation), D(glTexImage1D), D(glGetTexImage),
    D(glGetBufferSubData), D(glPolygonMode), D(glClampColor),

    /* ---- bloque 1: API completa ---- */
    D(glUniform1f), D(glUniform1i), D(glUniform1ui), D(glUniform2f), D(glUniform2i),
    D(glUniform2ui), D(glUniform3f), D(glUniform3i), D(glUniform3ui), D(glUniform4f),
    D(glUniform4i), D(glUniform4ui), D(glUniform1fv), D(glUniform1iv), D(glUniform1uiv),
    D(glUniform2fv), D(glUniform2iv), D(glUniform2uiv), D(glUniform3fv), D(glUniform3iv),
    D(glUniform3uiv), D(glUniform4fv), D(glUniform4iv), D(glUniform4uiv),
    D(glUniformMatrix2fv), D(glUniformMatrix3fv), D(glUniformMatrix4fv),
    D(glUniformMatrix2x3fv), D(glUniformMatrix3x2fv), D(glUniformMatrix2x4fv),
    D(glUniformMatrix4x2fv), D(glUniformMatrix3x4fv), D(glUniformMatrix4x3fv),
    D(glGetUniformfv), D(glGetUniformiv), D(glGetUniformuiv), D(glGetActiveUniform),
    D(glGetActiveUniformName), D(glGetActiveAttrib), D(glGetFragDataLocation),
    D(glVertexAttrib1f), D(glVertexAttrib1s), D(glVertexAttrib1d), D(glVertexAttrib1fv),
    D(glVertexAttrib1sv), D(glVertexAttrib1dv), D(glVertexAttrib2f), D(glVertexAttrib2s),
    D(glVertexAttrib2d), D(glVertexAttrib2fv), D(glVertexAttrib2sv), D(glVertexAttrib2dv),
    D(glVertexAttrib3f), D(glVertexAttrib3s), D(glVertexAttrib3d), D(glVertexAttrib3fv),
    D(glVertexAttrib3sv), D(glVertexAttrib3dv), D(glVertexAttrib4f), D(glVertexAttrib4s),
    D(glVertexAttrib4d), D(glVertexAttrib4fv), D(glVertexAttrib4sv), D(glVertexAttrib4dv),
    D(glVertexAttrib4Nub), D(glVertexAttrib4Nbv), D(glVertexAttrib4Nsv),
    D(glVertexAttrib4Nubv), D(glVertexAttrib4Nusv), D(glVertexAttrib4Nuiv),
    D(glVertexAttrib4bv), D(glVertexAttrib4iv), D(glVertexAttrib4ubv),
    D(glVertexAttrib4uiv), D(glVertexAttrib4usv), D(glVertexAttribI1i),
    D(glVertexAttribI1ui), D(glVertexAttribI1iv), D(glVertexAttribI1uiv),
    D(glVertexAttribI2i), D(glVertexAttribI2ui), D(glVertexAttribI2iv),
    D(glVertexAttribI2uiv), D(glVertexAttribI3i), D(glVertexAttribI3ui),
    D(glVertexAttribI3iv), D(glVertexAttribI3uiv), D(glVertexAttribI4i),
    D(glVertexAttribI4ui), D(glVertexAttribI4iv), D(glVertexAttribI4uiv),
    D(glVertexAttribI4bv), D(glVertexAttribI4sv), D(glVertexAttribI4ubv),
    D(glVertexAttribI4usv), D(glGetVertexAttribiv), D(glGetVertexAttribfv),
    D(glGetVertexAttribdv), D(glGetVertexAttribIiv), D(glGetVertexAttribIuiv),
    D(glGetVertexAttribPointerv), D(glFlushMappedBufferRange), D(glGetBufferPointerv),
    D(glTexImage2D), D(glTexImage3D), D(glTexSubImage2D), D(glTexSubImage3D),
    D(glCopyTexImage2D), D(glCopyTexSubImage2D), D(glCopyTexSubImage3D),
    D(glCompressedTexImage2D), D(glCompressedTexImage3D), D(glCompressedTexSubImage2D),
    D(glCompressedTexSubImage3D), D(glGenerateMipmap), D(glPixelStorei), D(glPixelStoref),
    D(glTexParameterf), D(glTexParameterfv), D(glTexParameteriv), D(glTexParameterIiv),
    D(glTexParameterIuiv), D(glGetTexParameteriv), D(glGetTexParameterfv),
    D(glGetTexParameterIiv), D(glGetTexParameterIuiv), D(glGetTexLevelParameteriv),
    D(glGetTexLevelParameterfv), D(glIsTexture), D(glGenFramebuffers),
    D(glDeleteFramebuffers), D(glBindFramebuffer), D(glIsFramebuffer),
    D(glCheckFramebufferStatus), D(glFramebufferTexture2D), D(glFramebufferTexture3D),
    D(glFramebufferTextureLayer), D(glFramebufferRenderbuffer),
    D(glGetFramebufferAttachmentParameteriv), D(glGenRenderbuffers),
    D(glDeleteRenderbuffers), D(glBindRenderbuffer), D(glIsRenderbuffer),
    D(glRenderbufferStorage), D(glRenderbufferStorageMultisample),
    D(glGetRenderbufferParameteriv), D(glBlitFramebuffer), D(glDrawBuffer),
    D(glDrawBuffers), D(glReadBuffer), D(glReadPixels), D(glClearBufferiv),
    D(glClearBufferuiv), D(glClearBufferfv), D(glClearBufferfi), D(glClear),
    D(glClearColor), D(glClearDepth), D(glClearStencil), D(glViewport), D(glScissor),
    D(glDepthRange), D(glDepthFunc), D(glDepthMask), D(glBlendFunc), D(glBlendFuncSeparate),
    D(glBlendEquation), D(glBlendEquationSeparate), D(glBlendColor), D(glStencilFunc),
    D(glStencilFuncSeparate), D(glStencilOp), D(glStencilOpSeparate), D(glStencilMask),
    D(glStencilMaskSeparate), D(glCullFace), D(glFrontFace), D(glColorMask),
    D(glColorMaski), D(glEnablei), D(glDisablei), D(glIsEnabledi), D(glPolygonOffset),
    D(glLineWidth), D(glPointSize), D(glHint), D(glSampleCoverage), D(glFlush), D(glFinish),
    D(glGetBooleanv), D(glGetFloatv), D(glGetDoublev), D(glIsShader), D(glIsProgram),
    D(glValidateProgram), D(glGetShaderSource), D(glGetAttachedShaders),
    D(glBeginTransformFeedback), D(glEndTransformFeedback), D(glTransformFeedbackVaryings),
    D(glGetTransformFeedbackVarying), D(glBeginConditionalRender),
    D(glEndConditionalRender),

    /* ---- bloque 2: funciones que existian pero no estaban publicadas ---- */
    D(glGetBooleani_v), D(glPointParameterf), D(glPointParameteri), D(glPointParameterfv),
    D(glPointParameteriv), D(glLogicOp), D(glFramebufferTexture1D), D(glTexStorage1D),

    /* ---- bloque 3: OpenGL 3.0 / 3.1 / 3.2 ---- */
    D(glClientWaitSync), D(glCompressedTexImage1D), D(glCompressedTexSubImage1D),
    D(glCopyTexImage1D), D(glCopyTexSubImage1D), D(glDeleteSync),
    D(glDrawElementsBaseVertex), D(glDrawElementsInstancedBaseVertex),
    D(glDrawRangeElementsBaseVertex), D(glFenceSync), D(glFramebufferTexture),
    D(glGetBufferParameteri64v), D(glGetCompressedTexImage), D(glGetInteger64i_v),
    D(glGetInteger64v), D(glGetMultisamplefv), D(glGetSamplerParameterIiv),
    D(glGetSamplerParameterIuiv), D(glGetSamplerParameterfv), D(glGetSynciv), D(glIsSync),
    D(glMultiDrawElementsBaseVertex), D(glProvokingVertex), D(glSampleMaski),
    D(glSamplerParameterIiv), D(glSamplerParameterIuiv), D(glSamplerParameterfv),
    D(glSamplerParameteriv), D(glTexImage2DMultisample), D(glTexImage3DMultisample),
    D(glTexSubImage1D), D(glWaitSync),

    /* ---- bloque 4: OpenGL 4.0 - 4.3 ---- */
    D(glActiveShaderProgram), D(glBindBuffersBase), D(glBindBuffersRange),
    D(glBindImageTexture), D(glBindImageTextures), D(glBindProgramPipeline),
    D(glBindSamplers), D(glBindTextures), D(glBindTransformFeedback), D(glBindVertexBuffer),
    D(glBindVertexBuffers), D(glBlendEquationSeparatei), D(glBlendEquationi),
    D(glBlendFuncSeparatei), D(glBlendFunci), D(glClearBufferData), D(glClearBufferSubData),
    D(glClearDepthf), D(glCopyImageSubData), D(glCreateShaderProgramv),
    D(glDebugMessageCallback), D(glDebugMessageControl), D(glDebugMessageInsert),
    D(glDeleteProgramPipelines), D(glDeleteTransformFeedbacks), D(glDepthRangeArrayv),
    D(glDepthRangeIndexed), D(glDepthRangef), D(glDispatchCompute),
    D(glDispatchComputeIndirect), D(glDrawArraysIndirect),
    D(glDrawArraysInstancedBaseInstance), D(glDrawElementsIndirect),
    D(glDrawElementsInstancedBaseInstance),
    D(glDrawElementsInstancedBaseVertexBaseInstance), D(glDrawTransformFeedback),
    D(glDrawTransformFeedbackInstanced), D(glDrawTransformFeedbackStream),
    D(glFramebufferParameteri), D(glGenProgramPipelines), D(glGenTransformFeedbacks),
    D(glGetActiveAtomicCounterBufferiv), D(glGetDebugMessageLog), D(glGetDoublei_v),
    D(glGetFloati_v), D(glGetFramebufferParameteriv), D(glGetInternalformativ),
    D(glGetObjectLabel), D(glGetProgramBinary), D(glGetProgramInterfaceiv),
    D(glGetProgramPipelineInfoLog), D(glGetProgramPipelineiv), D(glGetProgramResourceIndex),
    D(glGetProgramResourceLocation), D(glGetProgramResourceName), D(glGetProgramResourceiv),
    D(glGetShaderPrecisionFormat), D(glInvalidateBufferData), D(glInvalidateBufferSubData),
    D(glInvalidateFramebuffer), D(glInvalidateSubFramebuffer), D(glInvalidateTexImage),
    D(glInvalidateTexSubImage), D(glIsProgramPipeline), D(glIsTransformFeedback),
    D(glMemoryBarrier), D(glMemoryBarrierByRegion), D(glMinSampleShading),
    D(glMultiDrawArraysIndirect), D(glMultiDrawElementsIndirect), D(glObjectLabel),
    D(glPatchParameterfv), D(glPatchParameteri), D(glPauseTransformFeedback),
    D(glPopDebugGroup), D(glProgramBinary), D(glProgramParameteri), D(glProgramUniform1f),
    D(glProgramUniform1fv), D(glProgramUniform1i), D(glProgramUniform1iv),
    D(glProgramUniform1ui), D(glProgramUniform1uiv), D(glProgramUniform2f),
    D(glProgramUniform2fv), D(glProgramUniform2i), D(glProgramUniform2iv),
    D(glProgramUniform2ui), D(glProgramUniform2uiv), D(glProgramUniform3f),
    D(glProgramUniform3fv), D(glProgramUniform3i), D(glProgramUniform3iv),
    D(glProgramUniform3ui), D(glProgramUniform3uiv), D(glProgramUniform4f),
    D(glProgramUniform4fv), D(glProgramUniform4i), D(glProgramUniform4iv),
    D(glProgramUniform4ui), D(glProgramUniform4uiv), D(glProgramUniformMatrix2fv),
    D(glProgramUniformMatrix2x3fv), D(glProgramUniformMatrix2x4fv),
    D(glProgramUniformMatrix3fv), D(glProgramUniformMatrix3x2fv),
    D(glProgramUniformMatrix3x4fv), D(glProgramUniformMatrix4fv),
    D(glProgramUniformMatrix4x2fv), D(glProgramUniformMatrix4x3fv), D(glPushDebugGroup),
    D(glReleaseShaderCompiler), D(glResumeTransformFeedback), D(glScissorArrayv),
    D(glScissorIndexed), D(glScissorIndexedv), D(glShaderStorageBlockBinding),
    D(glTexBufferRange), D(glTexStorage2DMultisample), D(glTexStorage3DMultisample),
    D(glTextureView), D(glUseProgramStages), D(glValidateProgramPipeline),
    D(glVertexAttribBinding), D(glVertexAttribFormat), D(glVertexAttribIFormat),
    D(glVertexAttribLFormat), D(glVertexBindingDivisor), D(glViewportArrayv),
    D(glViewportIndexedf), D(glViewportIndexedfv),
};

void* gl31_get_proc_address(const char* name)
{
    size_t i;
    if (!name) return NULL;
    for (i = 0; i < sizeof(gl31_table) / sizeof(gl31_table[0]); i++)
        if (strcmp(gl31_table[i].name, name) == 0)
            return gl31_table[i].fn;
    return NULL;
}
